// Include any postdeployment steps here, such as steps necessary to test that the deployment was successful. If there are no postdeployment steps, leave this file empty.

== Postdeployment steps

=== Getting started

When you log in to the bastion host, HVR hub, or HVR agent, you see a message on using the images. Review the message. Also read the readme file located in the HVR Linux user home directory: */home/hvr/hvr-readme.txt*.

To start the HVR graphical user interface on the bastion host, connect to the host by using SSH with your supplied key pair. Connect as the HVR Unix user: `sudo su - hvr`. Then run `hvrwebdesktop`, and follow the instructions.

=== Restricted port access

**In the public subnets:**

* Inbound ports 22 and 8080 are open for connections to the bastion host.
** Port 22 is used for SSH access. You need a valid key pair to access the host.
** Port 8080 can be used to access the HVR web desktop to establish a remote connection to the HVR hub for configuration.
* Outbound traffic is limited to ports 22, 8080, 4343, and 443.
** The HVR hub and agents are behind Network Load Balancers using port 4343 for HVR communication.
** The bastion host can connect to the hub and agents using port 4343 and 22 (SSH). SSH requires the specified key pair.

**In the private subnets:**

*  Inbound ports are 4343, 22 and 2049.
** Port 4343 is used for HVR communication.
** Port 22 is used for SSH access. A valid key pair is required to access the host.
** Port 2049 is used for Amazon EFS.
* Outbound traffic is not limited.
